require: rubocop-rspec

AllCops:
  Exclude:
    - vendor/**/*

Metrics/AbcSize:
  Exclude:
    - spec/**/*

Style/FileName:
  Exclude:
    - lib/rubocop-facter.rb

Style/FileName:
  Exclude:
    - lib/rubocop-facter.rb

RSpec/FilePath:
  Exclude:
    - spec/project/default_config_spec.rb

Metrics/LineLength:
  Max: 100

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Style/MutableConstant:
  Enabled: true
